### PR TITLE
Bump version to 1.1.4.

### PR DESCRIPTION
**Pull request by alexmojaki**
The PR where these changes happened is here: https://github.com/yola/demands/pull/44

### CODE REVIEW

**Comment by adrianmoisey** [comment]
:+1:

**Comment by alexmojaki** [comment]
I have to upload to PyPi and YolaPI now right?

**Comment by adrianmoisey** [comment]
Yup

**Comment by alexmojaki** [comment]
Lol I closed without merging.

**Comment by adrianmoisey** [comment]
:laughing: :rocket:

**Pull request merged**
