### PR TITLE
Bump 1.1.5 with tag

### PR DESCRIPTION
**Pull request by alexmojaki**
See changelog.

### CODE REVIEW

**Comment by beck** [comment]
:+1:

**Comment by alexmojaki** [comment]
I added the tag, I can see it with `git tag -l`, but it bothers me that it shows up nowhere else. Not in `git status`, not in the `git push` output, not here. What's up with that?

**Comment by beck** [comment]
`git push --tags`

Make sure you're on `b51ac92` so the tagged code matches what is released

**Comment by alexmojaki** [comment]
I ran `git tag 1.1.5` just before `git commit -am "Bump to 1.1.5 for working release"`.
So what now? Do I have to revert this PR?
This is my first time dealing with tags, they make no sense to me.

**Comment by beck** [comment]
lets talk offline

**Comment by adrianmoisey** [comment]
> Make sure you're on b51ac92 when you tag 1.1.5 so the tagged code matches what is released

It should actually be 8fed57a.
Browsing https://github.com/yola/demands/tree/1.1.5 doesn't make sense now, since the changelog wasn't updated in this release.

**Comment by beck** [comment]
This one got loopy

How things went down:
* version bumped to 1.1.5
* pushed to master
* published
* master reverted, this pull opened
* version bumped to 1.1.5
* tagged (tagging at this point so the source matches what is published)
* changelog updated

**Comment by beck** [comment]
and @alexmojaki don't forget to delete the branch

**Pull request merged**
